[package]
name = "yil"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.1"
clap = "3.0.0-beta.2"
lexpr = "0.2.5"
tempfile = "3"
itertools = "0.10"
once_cell = "1.8.0"
